version: '3.4'
volumes: 
  m2_volume:
    name: m2_volume
services:
  envoy:
    build: ./envoy
    image: custom_envoy
    container_name: envoy
    ports:
      - "10000:10000"
  angular-demo:
    build: ./angular-demo
    image: angular-demo
    container_name: angular-demo
    ports:
      - 4200:80
  grpc-server:
    build: ./grpc-server
    image: grpc-server
    container_name: grpc-server
    volumes: 
      - type: volume
        source: m2_volume
        target: /root/.m2
    ports: 
      - 9090:9090